### ISSUE TITLE
 [ DB ] Unknown column 'node_name' in 'where clause'

### ISSUE THREAD

**Issue by nxtreaming** [coldsource/evqueue-core#3]
Unexpected exception : [ DB ] Unknown column 'node_name' in 'where clause'

caused by following query:
SELECT workflow_instance_id, workflow_schedule_id FROM t_workflow_instance WHERE workflow_instance_status='EXECUTING' AND node_name=''

Please sync 'create_tables_v1.4.sql'  and  "evqueue.conf"

Thanks.

**Comment by coldsource** [comment]
Hi, this is because we are working on version 1.5 (which will provide multi node clustering). You can checkout revision 1.4 which will work. Anyway I will try to fix in the week.

Regards,

**Comment by coldsource** [comment]
Hi, I just pushed create_tables_v1.5.sql.

evqueue.conf already contains default values for node name so everything should be alright.

The core is now ready to use multiple nodes and migrate tasks between nodes. We still have to work on the front end to provide accessibility to these functionnalities.

Regards,

**Comment by nxtreaming** [comment]
Thanks!

But where is the initial value of "network.node.name" ?

**Comment by coldsource** [comment]
Hi, the initial value is in Configuration.cpp :
https://github.com/coldsource/evqueue-core/blob/master/Configuration.cpp#L59

It is empty by default, which is the configuration for a single noded installation. For a multi node installation, this value must be set to a different value on each node.
