### ISSUE TITLE
Why do I always get error "The attribute 'queue' is required but missing" in GUI mode

### ISSUE THREAD

**Issue by nxtreaming** [coldsource/evqueue-core#4]
Action failed: saveWorkflow (Given XML does not validate against workflow.xsd: 
Line 1: Element 'task': The attribute 'queue' is required but missing.
)
![evequeue_error](https://cloud.githubusercontent.com/assets/3108107/11324991/bc2bf6a4-917c-11e5-8cb6-fcdd1300a165.png)

**Comment by nxtreaming** [comment]
I wanna add parameters for my workflow. But in Simple and Text mode I fail to add parameters for a specified workflow. It seems that only GUI mode supports add parameters

**Comment by coldsource** [comment]
Hi,

For the first problem, this is just the error message that is not very explicit. Setting a queue to each task is required. If you used the default init script you should have a queue named "default". The queue controls how many tasks can be launched simultaneously.

The simple mode is juste made to "mimic" a cron job. So the only thing you can do is launching a script with a fixed command line. It is made for easy creation of simple tasks.

If you want to create parameters and forward them to tasks, you should have a look at the documentation :
http://www.evqueue.net/doc/workflow-format
http://www.evqueue.net/doc/gui

It is possible in text mode, using the XML node "parameter" and also as you mentioned in the GUI mode.

Regards
