### ISSUE TITLE
Segfault still occurs 

### ISSUE THREAD

**Issue by wellingtonssilva-leishman** [coldsource/evqueue-core#6]
The release 2.1 says that segfault was solved. I don't know if it was the same reason but I'm getting the error in one of two nodes while starting:

May 30 19:52:09 <host ip> kernel: evqueue[2974]: segfault at 10 ip 00000000004f33a6 sp 00007f64362f3840 error 4 in evqueue[400000+1db000]

The error occurs after cluster discovery:
May 30 19:52:09 <host ip> evqueue: Discovering cluster

**Comment by wellingtonssilva-leishman** [comment]
It seens to be something on Cluster.cpp, with nodes. It stops when calling nodes.size()

`std::vector<std::string> Cluster::Ping(void)
{
	Logger::Log(LOG_INFO, "Discovering cluster");
	vector<string> res;
	for(int i=0;i<nodes.size();i++)
	{
		try
		{
			Client client(nodes.at(i),user,password);
			client.SetTimeouts(cnx_timeout,snd_timeout,rcv_timeout);		
			res.push_back(client.Connect());
			client.Disconnect();
		}
		catch(Exception &e)
		{
			// Errors are ignored in discovery mode
		}
	}
	return res;
}`

**Comment by coldsource** [comment]
Could you please test on head?
Thanks

**Comment by wellingtonssilva-leishman** [comment]
Hello,

Tried version 2.2, still same problem:

`May 31 09:47:30 <hostname> evqueue: Executing query : DROP TABLE IF EXISTS t_task
May 31 09:47:30 <hostname> evqueue: Executing query : ALTER TABLE t_datastore COMMENT='v2.2'
May 31 09:47:31 <hostname> evqueue: Executing query : ALTER TABLE t_log COMMENT='v2.2'
May 31 09:47:31 <hostname> evqueue: Executing query : ALTER TABLE t_log_api COMMENT='v2.2'
May 31 09:47:31 <hostname> evqueue: Executing query : ALTER TABLE t_notification COMMENT='v2.2'
May 31 09:47:31 <hostname> evqueue: Executing query : ALTER TABLE t_notification_type COMMENT='v2.2'
May 31 09:47:31 <hostname> evqueue: Executing query : ALTER TABLE t_queue COMMENT='v2.2'
May 31 09:47:31 <hostname> evqueue: Executing query : ALTER TABLE t_schedule COMMENT='v2.2'
May 31 09:47:31 <hostname> evqueue: Executing query : ALTER TABLE t_tag COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_uniqueaction COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_user COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_user_right COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_workflow COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_workflow_instance COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_workflow_instance_parameters COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_workflow_instance_tag COMMENT='v2.2'
May 31 09:47:32 <hostname> evqueue: Executing query : ALTER TABLE t_workflow_notification COMMENT='v2.2'
May 31 09:47:33 <hostname> evqueue: Executing query : ALTER TABLE t_workflow_schedule COMMENT='v2.2'
May 31 09:47:33 <hostname> evqueue: Executing query : ALTER TABLE t_workflow_schedule_parameters COMMENT='v2.2'
May 31 09:47:33 <hostname> evqueue: Executing query : SELECT table_comment FROM INFORMATION_SCHEMA.TABLES WHERE table_schema='evqueuedb' AND table_name='t_workflow_schedule'
...
...
...
May 31 09:47:49 <hostname> evqueue: Executing query : SELECT workflow_id, workflow_schedule, workflow_schedule_onfailure,workflow_schedule_host,workflow_schedule_user,workflow_schedule_active, workflow_schedule_comment, node_name FROM t_workflow_schedule WHERE workflow_schedule_id=5
May 31 09:47:49 <hostname> evqueue: Discovering cluster
May 31 09:47:49 <hostname> kernel: evqueue[17437]: segfault at 10 ip 00000000004f4d34 sp 00007fbaa28bc840 error 4 in evqueue[400000+1de000]
May 31 09:47:49 <hostname> systemd: evqueue.service: main process exited, code=killed, status=11/SEGV
May 31 09:47:49 <hostname> systemd: Unit evqueue.service entered failed state.
May 31 09:47:49 <hostname> systemd: evqueue.service failed.`

Regards

**Comment by coldsource** [comment]
This segfault occurs onstartup right?

I can't reproduce, what is your distribution?

**Comment by coldsource** [comment]
Could you please make a backup of the t_workflow_instance table and empty it?

The sql request to run: TRUNCATE t_workflow_instance;

Then try relaunching the engine. Tell me if it helps.

**Comment by wellingtonssilva-leishman** [comment]
I'm running a cluster with 2 nodes.

I updated the second node with version 2.2, and have no problem with second node.

Before truncate the second node was working, the second one no.
After Truncate  t_workflow_instance both nodes stopped working.
After restore second node worked again, the first one no. But the process that was running when I stopped the cluster didn't was resumed, it still are on executing workflows, but didin't has a process executing on server, and as it identify as running, don't start a new one.

OS: CentOS Linux release 7.6.1810 (Core)

**Comment by wellingtonssilva-leishman** [comment]
About services that core shows as running, but wasn't really running.
I tried to remove from table only workflows with EXECUTING status, after remove those, the core on second node (was working) didn't starts and shows segfault error also, restoring again it works again. So there is something that maybe is validated while starting, and as it didn't get expected response, it crashes.

Regards

**Comment by coldsource** [comment]
I have seen your other message on evqueue-frontend, did you finally get everything working?

If no here are more informations:

The workflow XML format has changed between version 2.1 and 2.2 so this is normal that you have problems with running workflows on upgrade. It is mandatory to remove them before upgrade.

I wasn't aware that you have 2 nodes. To upgrade you have to:
- stop all running nodes
- remove running instances from database
- launch only one node and wait for it to be running. It will perform necessary database upgrades
- launch other nodes

We have successfuly upgraded 4 nodes like this but maybe your configuration is a bit different.

If you still get segfault, I can show you how to compile with debug support so we can have a stacktrace I can work on. Other option is that you make me a database dump so I can test with your data and see what is going wrong.

Regards

**Comment by wellingtonssilva-leishman** [comment]
When I told everything working, I was speaking about frontend.

I already tried those steps, stopped all nodes, removed running(executing) instances from database, trued to start just one node, but it still crashes.
I didn't know about the mandatory step to remove workflows, but I didn't understand why after the upgrade (without removing the workflows) the second node starts, and works well with all flows that wasn't running when it stopped (so I think the problem was on resume). I just get error on that while tried to remove the "executing" workflows, on that scenario I get segfault.

I think we have 2 issues here: 

1. When trying to resume something that was running
On that case, the core stopped on this step when found "pending" workflows for that node, and didn't get on workflows table to see the xml v2.1 format. So it starts, but didn't call the same workflow anymore, even if scheduled. So probably when it gets solved, we gonna stop on issue 2.

2. When we have nothing to resume, it gets segfault. It can be because it gets on step that reads xml v2.1 format, so it crashs with segfault.

It just worked again when I dropped all tables and started again from scratch. Now is everything working, but we "lost" two important things, all workflows that was created and all schedulers already configured.

So, if I could, I would like to suggest an update on docs with that information about mandatory steps (sorry if it exists, but I didn't found it) and also if possible a tool to convert the old xml format to new one, to keep the retro compatibility.

Thanks again, I really like this tool.

**Comment by wellingtonssilva-leishman** [comment]
There is other segfault error that always happen (on previous and current version)

When creating a new scheduled workflow, it freezes for a few seconds, saves the schedule duplicated and one node goes down with segfault error.

`May 31 14:45:14 <hostname> evqueue: Accepting new connection, current connections : 2
May 31 14:45:14 <hostname> evqueue: Accepted connection from 172.16.45.127:46864
May 31 14:45:14 <hostname> evqueue: Unexpected exception in context Query XML parsing : Invalid
 query XML structure : invalid document structure
May 31 14:45:14 <hostname> evqueue: Ending connection, current connections : 1
May 31 14:45:14 <hostname> kernel: evqueue[8654]: segfault at c9 ip 000000000050c669 sp 00007f5
a28a718e0 error 4 in evqueue[400000+1de000]
May 31 14:45:14 <hostname> systemd: evqueue.service: main process exited, code=killed, status=1
1/SEGV
`
It seens that when a click to save, it calls this function on both nodes and it generate some conflict, so it crashes

Regards

**Comment by coldsource** [comment]
Thanks for the feedback.

Version 2.2 has a tool that converts workflows from v2.1 when it detects older formats and I guess this is why you get segfaults. If you send be a database dump I can work on this so you can keep workflows and schedules.

I will try to reproduce the segfault on schedule creation and patch is as soon as possible.

**Comment by wellingtonssilva-leishman** [comment]
[evquedb.zip](https://github.com/coldsource/evqueue-core/files/3244415/evquedb.zip)

**Comment by wellingtonssilva-leishman** [comment]
Hello,

I "found" the root cause, it was the network latency. I was running the evqueue-core in a server running on AWS (us-east), but DB was running on AWS (sa-east), after moving DB to us-east the errors 
stopped.

But I think it still need to be "solved", maybe a message instead of segfault during latency or slow scenario.

Regards,

Wellington

**Comment by coldsource** [comment]
Hi and sorry for replying so late.

Could you please dump database with structure. Here I have only data. It will be more easy to debug.

Thanks

**Comment by smalot** [comment]
This issue only occurs in an upgrade context ?

Which "Version 2.2" are you talking about ?

**Comment by wellingtonssilva-leishman** [comment]
@smalot no, I was getting segfault also before upgrade. But I just figured out this after the upgrade problem. 
The evqueue process some times, just stopped. But I think that as on upgrade we have more db activity, so it aways happen during upgrade.

**Comment by coldsource** [comment]
Hi, we are talking of the latest version which has not yet been released. It is the current git version, which will fi ally be version 3.0 because of the incompatibilities with previous version.

Segfault should not occur otherwise. We are running evqueue in production with uptimes of 300+ days on multiple nodes.

If you encounter any problems please let us know we will be glad to debug that!
