### ISSUE TITLE
Building evqueue-core on Debian 10 (Buster)

### ISSUE THREAD

**Issue by dobbers** [coldsource/evqueue-core#7]
If you try to build evqueue-core on Buster you will find that it requires a Curl library which is not mentioned in the build guide - this is the error it will return:
```
[ 61%] Linking CXX executable evqueue
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/evqueue.dir/build.make:1359: evqueue] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/evqueue.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
To get round this problem, install the following curl library and try the build again:

`sudo apt install -y libcurl4-openssl-dev`

**Comment by coldsource** [comment]
Thanks for your feedback, we'll update the documentation !
